[package]
name = "thermal-maps"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
egui = "0.31.1"
egui-file-dialog = "0.10.0"
egui-macroquad = "0.17.3"
image = { version = "0.25.6", features = ["bmp"] }
macroquad = "0.4.14"
